# Generated by Django 4.0.2 on 2022-06-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.CharField(blank=True, max_length=5)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('data', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
