# Generated by Django 4.0.2 on 2022-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarto', models.CharField(blank=True, max_length=2)),
                ('descricao', models.CharField(blank=True, max_length=50)),
                ('quantidade', models.CharField(blank=True, max_length=2)),
                ('valor_total', models.CharField(blank=True, max_length=8)),
                ('valor_unitario', models.CharField(blank=True, max_length=8)),
                ('datahora', models.CharField(blank=True, max_length=10)),
                ('valor_quarto', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
