# Generated by Django 4.0.2 on 2022-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarto', models.CharField(blank=True, max_length=2)),
                ('veiculo', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('placa', models.CharField(blank=True, max_length=7)),
            ],
        ),
    ]
