# Generated by Django 4.0.2 on 2022-06-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='data',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
