# Generated by Django 4.0.2 on 2022-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=5)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('valorunitario', models.CharField(blank=True, max_length=8)),
                ('quantidade', models.CharField(blank=True, max_length=5)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('data', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
