# Generated by Django 4.0.2 on 2022-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=10)),
                ('codigo', models.CharField(blank=True, max_length=10)),
                ('quarto', models.CharField(blank=True, max_length=5)),
                ('entrada', models.CharField(blank=True, max_length=10)),
                ('saida', models.CharField(blank=True, max_length=10)),
                ('total', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
