# Generated by Django 4.0.2 on 2022-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(blank=True, max_length=200)),
                ('fantasia', models.CharField(blank=True, max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=14)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=5)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=11)),
                ('telefone2', models.CharField(blank=True, max_length=11)),
                ('telefone3', models.CharField(blank=True, max_length=11)),
            ],
        ),
    ]
