# Generated by Django 4.0.2 on 2022-05-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ig',
            name='tabela_preco',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
