# Generated by Django 4.0.2 on 2022-05-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0002_ig_tabela_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ig',
            name='tabela_preco',
        ),
    ]
