# Generated by Django 4.0.2 on 2022-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emeil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('senha', models.CharField(blank=True, max_length=20)),
                ('smtp', models.CharField(blank=True, max_length=50)),
                ('porta', models.CharField(blank=True, max_length=10)),
                ('timeout', models.CharField(blank=True, max_length=2)),
                ('email_destino', models.CharField(blank=True, max_length=100)),
                ('email_contabilidade', models.CharField(blank=True, max_length=100)),
                ('autenticacao', models.BooleanField()),
            ],
        ),
    ]
