# Generated by Django 4.0.2 on 2022-06-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='nome',
            new_name='camareira',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='idade',
        ),
        migrations.AddField(
            model_name='dados',
            name='codigo',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='dados',
            name='dia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dados',
            name='quarto',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
