# Generated by Django 4.0.2 on 2022-06-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='horas_diaria',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='horas_locacao',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='tempo_adicional',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='tempo_especial',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='tolerancia',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='valor_adicional',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='valor_diaria',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='valor_especial',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='valor_locacao',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='vh1',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='vh2',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='vh3',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='vh4',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='vh5',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='vh6',
        ),
    ]
