# Generated by Django 4.0.2 on 2022-05-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='tipo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
