# Generated by Django 4.0.2 on 2022-06-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_locacao', models.CharField(blank=True, max_length=2)),
                ('valor_locacao', models.CharField(blank=True, max_length=8)),
                ('tempo_especial', models.CharField(blank=True, max_length=2)),
                ('valor_especial', models.CharField(blank=True, max_length=8)),
                ('horas_diaria', models.CharField(blank=True, max_length=2)),
                ('valor_diaria', models.CharField(blank=True, max_length=8)),
                ('tempo_adicional', models.CharField(blank=True, max_length=2)),
                ('valor_adicional', models.CharField(blank=True, max_length=2)),
                ('tolerancia', models.CharField(blank=True, max_length=2)),
                ('vh1', models.CharField(blank=True, max_length=8)),
                ('vh2', models.CharField(blank=True, max_length=8)),
                ('vh3', models.CharField(blank=True, max_length=8)),
                ('vh4', models.CharField(blank=True, max_length=8)),
                ('vh5', models.CharField(blank=True, max_length=8)),
                ('vh6', models.CharField(blank=True, max_length=8)),
            ],
        ),
    ]
